Vagrant.configure("2") do |config|
  config.vm.box = "boxcutter/ubuntu1604"

  config.omnibus.chef_version = "13.0.118"

  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "."
    chef.add_recipe "myapp_chef"
  end

end
